[parity_pack]
git-tree-sha1 = "c7353f05cb079034198de322f9dcfae7f9feaf68"
lazy = true

    [[parity_pack.download]]
    sha256 = "b2ceaed1c8b44ed95b1180fc33e2a771b5463f1d08b8c4c91729cb32e335398e"
    url = "https://github.com/Rasoolpey/Porthos.jl/releases/download/parity-pack-v3/parity_pack-v3.tar.gz"
